apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi # Match pods with the 'app: fastapi' label
  ports:
    - protocol: TCP
      port: 5001  # Port to access the FastAPI application
      targetPort: 5001  # Target port on the pods
  type: NodePort  # Service type as NodePort
