version: '3'

services:
  mariadb-service:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: storedb
      MYSQL_USER: root
      MYSQL_PASSWORD: "1234"
    ports:
      - 3308:3306
