services:
  mariadb-service:
    container_name: mariadb-container
    build:
      context: ./config
      dockerfile: Dockerfile  
    restart: always
    ports:
      - "3308:3306" # innecesario

  api-service:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb-service
    ports:
      - "5001:5001"