version: '3'

services:
  api-service:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb-service
    ports:
      - 5001:8000

  mariadb-service:
    container_name: mariadb-container
    build:
      context: ./config
      dockerfile: Dockerfile  
    restart: always
    ports:
      - 3308:3306